# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c32b70f97d663354555b1a26fc19129fd1c4b0be3bf51e4bc7c8baca66bebdc07620335f86ad563b78a913d2327ee6d57e47c3c53bcce17ec864e77f9608276c

test:
  secret_key_base: b2a0bf9187eadaa402cad79197523070c53847a22b4a464c415c2cd3b3b2f08c03ad19409ca661682c0693afc702b5101862dd076e0f13df2edc9e518d1cc718

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
